# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Analysis Airbnb Cleaned Europe data
author: Shengnan Li
copyright: "2023"
logo: berkeley-logo-white.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

only_build_toc_files: False


# Information about where the book exists on the web
repository:
  url: https://github.com/PPN271/stat_159_final.git  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true